version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  cloud-config:
    build:
      context: .              
      dockerfile: cloud-config/Dockerfile
    ports:
      - "9296:9296"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  service-discovery:
    build:
      context: .
      dockerfile: service-discovery/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - cloud-config
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
      - user-service
      - order-service
      - product-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8700:8700"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile

    ports:
      - "8300:8300"
    depends_on:
      - service-discovery
      - user-service
      - product-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8500:8500"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
