apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  ports:
  - port: 8300
    protocol: TCP
    targetPort: 8300
  selector:
    app: order-service
  type: ClusterIP 