apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: product-service
  type: ClusterIP 