apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: cloud-config
          image: ecommerceacr.azurecr.io/cloud-config:v8
          ports:
            - containerPort: 9296
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
spec:
  selector:
    app: cloud-config
  ports:
    - protocol: TCP
      port: 9296
      targetPort: 9296
  type: ClusterIP