server:
  port: 8700

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_db}
    username: ${DB_USERNAME:psqladmin}
    password: ${DB_PASSWORD:Password1234!}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: false
  #flyway:
  #  baseline-on-migrate: true
  #  enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

