name: Product Service CI/CD

# 1. TRIGGER: Se activa con un push o pull request a la rama 'main', 
# pero solo para cambios dentro del directorio 'product-service'.
on:
  push:
    branches:
      - main
    paths:
      - 'product-service/**'
      - '.github/workflows/product-service-ci-cd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'product-service/**'

# Variables de entorno disponibles para todos los jobs
env:
  ACR_NAME: ecommerceacr             # <-- REEMPLAZA con el nombre de tu ACR
  AKS_CLUSTER_NAME: ecommerceaks     # <-- REEMPLAZA con el nombre de tu clúster AKS
  AKS_RESOURCE_GROUP: ecommerce-rg    # <-- REEMPLAZA con el Resource Group de tu AKS
  IMAGE_NAME: product-service

jobs:
  build_and_deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest
    
    steps:
    # 2. CHECKOUT: Clona tu repositorio para que el pipeline pueda acceder al código.
    - name: Checkout repository
      uses: actions/checkout@v3

    # 3. SETUP JAVA & MAVEN: Instala Java 11 para construir el proyecto.
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # 4. BUILD JAR: Ejecuta Maven para compilar y empaquetar el código en un .jar.
    #    working-directory asegura que el comando se ejecute en la carpeta del microservicio.
    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: ./product-service

    # 5. AZURE LOGIN: Se autentica en Azure usando el secreto que creaste.
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io


    # 6. BUILD & PUSH DOCKER IMAGE: 
    #    Construye la imagen y la sube a ACR.
    #    Usa el GitHub SHA (identificador único del commit) como etiqueta para la imagen.
    #    Esto asegura que cada push tenga una imagen única.
    - name: Build and push Docker image to ACR
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
      working-directory: ./product-service
      
    # 7. SET AKS CONTEXT: Configura kubectl para que apunte a tu clúster de AKS.
    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    # 8. DEPLOY: Usa kubectl para aplicar el manifiesto.
    #     OJO: Este es el paso que iremos mejorando. Por ahora, asumimos que tienes un manifiesto base.
    #     La forma más simple de actualizar la imagen es con `kubectl set image`.
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/product-service-deployment product-service=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} -n default
    
    # 9. VERIFY DEPLOYMENT: Revisa que el despliegue se haya completado exitosamente.
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/product-service-deployment -n default 
