name: Product Service CI

# 1. TRIGGER: Este workflow se ejecuta en un push a la carpeta del servicio.
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'product-service/**'
      - '.github/workflows/product-service-ci.yml'
      - '.github/workflows/reusable-microservice-ci.yml'

jobs:
  call_reusable_workflow:
    name: Build & Deploy Product Service
    # 2. USES: Llama al workflow reutilizable que creamos.
    uses: ./.github/workflows/reusable-microservice-ci.yml
    # 3. WITH: Proporciona los inputs que el workflow reutilizable necesita.
    with:
      service_name: product-service
      service_path: ./product-service
    # 4. SECRETS: Pasa todos los secretos del repositorio al workflow reutilizable.
    secrets:
      ACR_NAME: ${{ vars.ACR_NAME }}
      AKS_CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME }}
      AKS_RESOURCE_GROUP: ${{ vars.AKS_RESOURCE_GROUP }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 